apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo
  namespace: argo-rollouts
spec:
  interval: 5m
  releaseName: argo
  chart:
    spec:
      chart: argo-rollouts
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: flux-system
