apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-nats
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: nats
      version: '2.4.0'
      sourceRef:
        kind: HelmRepository
        name: my-nats
        namespace: flux-system
      interval: 1m
